export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue color ,128 GB storage',
      price: '89999',
    },
    
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/41TR7G8VboL._SY445_SX342_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White color ,128 GB storage',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro 8GB,256GB,',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Google pixel 8 pro",
      imgSrc: 'https://m.media-amazon.com/images/I/61NfiSBRwfL._SX679_.jpg',
      amazonLink: 'https://amzn.in/d/9RqbD5W',
      description: 'Pixel 8 Pro 5G Smartphone (12GB Ram 128GB )',
      price: '69999',
    },
    {
      id: 11,
      category: 'mobiles',
      title: "Apple iphone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/314Rp+8XKWL._SX342_SY445_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue color ,128 GB storage',
      price: '69999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB',
      price: '49999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
      id: 15,
      category: 'laptops',
      title: "Dell Alienware m18 R1",
      imgSrc: 'https://m.media-amazon.com/images/I/414CpWCOoHL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.in/d/7Y2LgPV',
      description: 'Dell Alienware m18 R1, Intel Core i9-13980HX Processor/64GB/1TB SSD ,RTX 4090',
      price: '455000',
    },
    {
      id: 10,
      category: 'mobiles',
      title: "Oneplus 10R",
      imgSrc: 'https://oasis.opstatics.com/content/dam/oasis/page/2022/operation/apr/in/10r-green.png',
      amazonLink: 'https://amzn.in/d/j6AwtPm',
      description: 'Display: 6.7 Inches; 120 Hz IRIS Display; Resolution: 2400 X 1080 pixels 394 ppi ',
      price: '29999',
    },
    {
      id: 10,
      category: 'earphones',
      title: "JBL wave beam wireless earbuds",
      imgSrc: 'https://m.media-amazon.com/images/I/61e+AB+vO1L._AC_UY218_.jpg',
      amazonLink: 'https://amzn.in/d/72igF0Y',
      description: 'JBL Wave Beam in-Ear Wireless Earbuds (TWS) with Mic,App fExtra Bass Eq',
      price: '2998',
    },
    {
      id: 10,
      category: 'earphones',
      title: "Boat Atom 81 pro earbuds",
      imgSrc: 'https://m.media-amazon.com/images/I/61DRIWg+rNL._AC_UY218_.jpg',
      amazonLink: 'https://m.media-amazon.com/images/I/61DRIWg+rNL._AC_UY218_.jpg',
      description: 'boAt Atom 81 Pro ,50Ms ',
      price: '1999',
    },
    {
      id: 17,
      category: 'earphones',
      title: "Boult Audio W20 earbuds",
      imgSrc: 'https://m.media-amazon.com/images/I/710dy4BFjLL._SY450_.jpg',
      amazonLink: 'https://amzn.in/d/3gyVBHA',
      description: '35H Playtime, Zen™ ENC Mic, 45ms Low Latency, 13mm Bass Drivers, Type-C Fast Charging,   best seller',
      price: '1599',
    },
    {
      id: 20,
      category: 'earphones',
      title: "ZEBRONICS Duke Plus headphone",
      imgSrc: 'https://m.media-amazon.com/images/I/619w5E8UpbL._SY450_.jpg',
      amazonLink: 'https://amzn.in/d/gHUGfez',
      description: ' Wireless Over Ear Headphone with ANC, ENC, Gaming Mode,',
      price: '2599',
    },
    {
      id: 18,
      category: 'watches',
      title: "Fastrack smartwatch",
      imgSrc: 'https://m.media-amazon.com/images/I/41tps1-sn4L._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.in/d/1JsOzhy',
      description: 'Advanced UltraVU HD Display|BT Calling|Advance Chipset85+ Sports Modes & Watchfaces',
      price: '1399',
    },
    {
      id: 19,
      category: 'watches',
      title: "Fossil Nate Analog watch ",
      imgSrc: 'https://m.media-amazon.com/images/I/71kbRVr8YfL._SX679_.jpg',
      amazonLink: 'https://amzn.in/d/iQm7BdZ',
      description: 'Fossil Nate Chronograph Analog Black Dial Grey Band Mens Stainless Steel Watch - JR1401',
      price: '15499',
    },
    {
      id: 21,
      category: 'watches',
      title: "Titan Men's watch ",
      imgSrc: 'https://m.media-amazon.com/images/I/51qHC1wPnsL._SX679_.jpg',
      amazonLink: 'https://amzn.in/d/0epJbms',
      description: 'Mens Multifunctional Black Watch with Metallic Accents-NS1805NM02, AI Search,',
      price: '15499',
    },
    {
      id: 22,
      category: 'watches',
      title: "Noise Pulse 4 Max Smart Watch",
      imgSrc: 'https://m.media-amazon.com/images/I/41-kupNvIeL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.in/d/8fRIoV8',
      description: ' AI Create (Indias 1st Ever with Unlimited Watch Faces), AI Search,',
      price: '15499',
    },


  ]